### PR TITLE
A bunch of flashing doc updates, including how to recover a device that isn't getting back to toboot after first flash, fixing udev, and flashing from chrome browser

### PR DESCRIPTION
**Pull request by marcmerlin**

### CODE REVIEW

**Comment by mithro** [comment]
@marcmerlin - BTW It should work without root if you have the udev rules installed.

**Comment by marcmerlin** [comment]
I'm sending a new/better version

**Comment by marcmerlin** [comment]
Just FYI, I got ATTRS{idVendor}=="0483", ATTRS{idProduct}=="cdab" from https://tomu.im/tomu.html which @mithro  recommended, but the USB numbers don't match on my tomus. I left it as the first line in case it's needed for other tomus.

**Comment by xobs** [comment]
The vendor ID `0x0483` appears to be from ST: https://www.the-sz.com/products/usbid/index.php?v=0x0483

Likely someone had an ST product present in their system when they looked at the output. ST has their own, incompatible implementation of DFU. The page you linked to is incorrect -- I'll update it now, thanks for pointing that out!

**Comment by marcmerlin** [comment]
Thanks @xobs  . I cleaned this up a bit. Is it good for merge now?

**Comment by marcmerlin** [comment]
I know that tomu is not the new hotness, but @mithro  are you ok merging those doc updates and fixes?

**Review by mithro — APPROVED** [review]
These updates LGTM.

@xobs could you merge?

**Pull request merged**
