### PR TITLE
Update usb-hid-keyboard.c

### PR DESCRIPTION
**Pull request by GuyNoIRQ**
Extended ascii conversions to keyboard mappings
Improved efficiently of ascii conversions to keyboard mappings
Added some comments documenting common mod chars
Added some additional non-ascii control chars
Fixed the issue with not being able to type multiple identical chars back to back
Wrote new sample injection scripts to show some of the new functionality

### CODE REVIEW

**Comment by xobs** [comment]
Thanks for the PR!

It looks like you now call `run_powershell()` instead of `run_notepad()`. Is that function defined anywhere? It doesn't appear to be part of the PR.

**Comment by GuyNoIRQ** [comment]
Hey, no problem.

Sorry I actually meant to pull that out completely since its just as easy to run super + r then inject whatever string and return.
Are you able to just yank that line out, or should I re-submit a new PR? Sorry I'm pretty rusty with both C and github.

**Comment by xobs** [comment]
You ought to be able to add those lines back in, do `git commit --amend`, and do `git push -f`, which will update the PR.

Or you can add it as another patch on top.

**Comment by GuyNoIRQ** [comment]
@xobs Ok I think I managed to get a new commit into my fork's master which I believe is now part of this PR. If it doesn't look right please let me know and I'll have a second go at this.

I just pulled that function declaration out as that bad usb sample script shows how to do something like that rather trivially.

If you'd really like for me to re-add a function specific to getting a given thing pop open via windows run command I can, but in my opinion its not really worth it to have a dedicated function for this. Sure it reduced the number of lines needed to be defined, but:

1: Its pretty trivial to issue win + r via the injkeys function then invoke injkeys again to inject the string for what you want to run + carriage return.
2: I think super + r is relevant only for windows so its pretty OS specific unless someone added that hotkey to linux/mac manually.
3: There are a few different ways to pop a given program open on Windows so having a dedicated function may be misleading as at present we would only really be able to perform one method with the assumption it will work on the given system. Maybe if I can manage to build in some kind of control channel via serial / ram fs / toggling the caps lock led to let the OS talk back to the tomu these kinds of functions may be worthwhile, but that is rather more involved.

**Comment by xobs** [comment]
No worries, the intention there was to just show an example of how you might do a thing. But given that it's so platform-specific, you're right in that it might not be that useful.

At any rate, I went ahead and merged it. Thanks for your contribution!

**Pull request merged**
